### ISSUE TITLE
Recommendations (Performance Enhancements)

### ISSUE THREAD

**Issue by bstahlhood** [distributed-lab/nest-template#1]
You guys should look into using Fastify over Express. In most cases you will see a 2x improvement in latency/RPS.

Also, you should look into logging with `Pino` vs `Winston`. Pino uses async / buffering to minimize the impact from logging.

https://docs.nestjs.com/techniques/performance

Good article on Logging impact: https://www.nearform.com/blog/the-cost-of-logging-in-2022/

- Ben

**Comment by velykodnyi** [comment]
Hello, thank you for your attention to our project. We plan to prepare roadmap in near future with improvements for this template. We will add there possible enhancement with fastify, replacing logs and, maybe, replacing typeorm
